test: *.jl
	~/julia-1.6.0/bin/julia ../tools/gentest.jl *.jl
	mv runtests.jl ../test
	~/julia-1.6.0/bin/julia ../test/runtests.jl
test16: *.jl
	~/julia-1.6.0/bin/julia ../tools/gentest.jl *.jl
	mv runtests.jl ../test
	~/julia-1.6.0/bin/julia ../test/runtests.jl
